[colors.primary]
background = "#030104"
foreground = "#daccd4"

[colors.cursor]
text = "#030104"
cursor = "#daccd4"

[colors.vi_mode_cursor]
text = "#030104"
cursor = "#daccd4"

[colors.search.matches]
foreground = "#030104"
background = "#daccd4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#988e94"
background = "#daccd4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#030104"
red = "#8F5D7A"
green = "#413999"
yellow = "#254D9C"
blue = "#8A0190"
magenta = "#916B9E"
cyan = "#1597D2"
white = "#daccd4"

[colors.bright]
black = "#988e94"
red = "#8F5D7A"
green = "#413999"
yellow = "#254D9C"
blue = "#8A0190"
magenta = "#916B9E"
cyan = "#1597D2"
white = "#daccd4"

[colors.dim]
black = "#daccd4"
red = "#8F5D7A"
green = "#413999"
yellow = "#254D9C"
blue = "#8A0190"
magenta = "#916B9E"
cyan = "#1597D2"
white = "#988e94"
